name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pre-commit/action@v2.0.3
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Run tests
        run: |
          source $VENV
          pytest "tests/"
  check-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    needs: test
    # Always try to build the documentation!
    # if: ${{ github.event_name == 'push' }}
    steps:
      - name: Set up Git
        uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Build documentation
        run: |
          source $VENV
          sphinx-build docs docs/_build
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4.2.5
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: docs/_build
  release:
    name: Release new version on GitHub
    runs-on: ubuntu-latest
    needs: check-documentation
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Set up Git
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set-Up poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12
      - name: Install library
        run: poetry install --no-interaction
      - name: Build documentation
        run: |
          source $VENV
          sphinx-build docs docs/_build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build
      - name: Run release script
        run: bash .auto/run_auto.sh
        env:
          # To be able to trigger publish event
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
