name: Test
on:
  push:
    branches: [main]
    paths-ignore:
      - "bigearthnet_common/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "bigearthnet_common/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
